export const HOME = '/'
export const ABOUT_US = '/about'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const FORGOT_PASSWORD = '/forgot'
export const FORGOT_PASSWORD_ID = "/forgot/:temporaryKey";
// export const PRODUCTS = "/products"
export const PRODUCTS_CATEGORY = "/products/:category"
export const ERROR = "*"
// Profile
export const PROFILE = '/profile'
export const PROFILE_MY_ORDERS = '/profile/my-orders'
export const PROFILE_ACCOUNT = '/profile/account'
export const PROFILE_PASSWORD = '/profile/password'
export const PROFILE_ADDRESSES = '/profile/addresses'
export const PROFILE_ADDRESSES_ID = "/profile/addresses/:id";
export const PROFILE_PAYMENT_METHODS = "/profile/payment-methods"
export const PROFILE_PAYMENT_METHODS_ID = "/profile/payment-methods/:id";
export const PROFILE_PAYMENT_HISTORY = "/profile/payment-history";
export const PROFILE_NOTIFICATIONS = "/profile/notifications";
